name: NodeJS with Webpack

on:
  push:
    branches: [ development ]
  # pull_request:
  #   branches: [ development ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.RESTAURANT_NINJA_PROD }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        echo ${{ secrets.RESTAURANT_NINJA_PROD }}
        echo ${{ secrets.SSH_HOST }}
        git submodule update --init --recursive
        npm install
        npm run buildOnLinux

    - name: Deploy
      run: scp -r public root@${{ secrets.SSH_HOST }}:/home/upload

    - name: Trigger restart
      run: ssh -t root@${{ secrets.SSH_HOST }} "bash /home/update.sh"
